name: Deploy to Firebase Hosting Dmaorg
'on':
  push:
    branches:
      - dmaorg-archive

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: twentyonepilots-wiki
          TARGET_BRANCH: dmaorg-archive
          TARGET_NAME: dmaorg