name: Deploy to Firebase Hosting Dmaorg
'on':
  push:
    branches:
      - dmaorg-archive

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install firebase tools
        run: |
          sudo npm install -g firebase-tools
          firebase use twentyonepilots-wiki --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        run: firebase deploy --only hosting:dmaorg --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"