name: Deploy to Firebase Hosting Preview on merge
'on':
  push:
    branches:
      - dmaorg-archive

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Hugo
        uses: lowply/build-hugo@v0.68.3
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.3
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWENTYONEPILOTS_WIKI }}'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          FIREBASE_PROJECT: name-of-the-project
          TARGET_BRANCH: dmaorg-archive
          TARGET_NAME: dmaorg